In [2]:
from PIL import Image
import numpy as np

num = '2'

im = Image.open('/home/what_is_love/Lab/maps/' + num + '/map.png')
p = np.array(im)
m = p[::,::,1]
m = m/255
m = abs(m-1)
m = m.astype(int)

f = open('/home/what_is_love/Lab/maps/' + num + '/map.txt', 'w')
f.write(str(m.shape[0]) + ' ' + str(m.shape[1]) + '\n')
f.write('5 4 \n85 85 \n')
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        f.write(str(j+1) + ' ' + str(i+1) + ' ' + str(m[i][j]) + '\n')


        
f.close()


In [8]:
from PIL import Image
import numpy as np

num = '5'

im = Image.open('/home/what_is_love/Lab/maps/' + num + '/map.png')
p = np.array(im)
m = p[::,::,]

print(np.argwhere(m == [0, 0, 0]))



[[ 0  0  0]
 [ 0  0  1]
 [ 0  0  2]
 [ 0  1  0]
 [ 0  1  1]
 [ 0  1  2]
 [ 0  2  0]
 [ 0  2  1]
 [ 0  2  2]
 [ 0  3  0]
 [ 0  3  1]
 [ 0  3  2]
 [ 0  4  0]
 [ 0  4  1]
 [ 0  4  2]
 [ 0  5  0]
 [ 0  5  1]
 [ 0  5  2]
 [ 0  6  0]
 [ 0  6  1]
 [ 0  6  2]
 [ 0  7  0]
 [ 0  7  1]
 [ 0  7  2]
 [ 0  8  0]
 [ 0  8  1]
 [ 0  8  2]
 [ 0  9  0]
 [ 0  9  1]
 [ 0  9  2]
 [ 0 10  0]
 [ 0 10  1]
 [ 0 10  2]
 [ 1  0  0]
 [ 1  0  1]
 [ 1  0  2]
 [ 1 10  0]
 [ 1 10  1]
 [ 1 10  2]
 [ 2  0  0]
 [ 2  0  1]
 [ 2  0  2]
 [ 2  2  0]
 [ 2  2  1]
 [ 2  2  2]
 [ 2  8  0]
 [ 2  8  1]
 [ 2  8  2]
 [ 2 10  0]
 [ 2 10  1]
 [ 2 10  2]
 [ 3  0  0]
 [ 3  0  1]
 [ 3  0  2]
 [ 3  4  0]
 [ 3  4  1]
 [ 3  4  2]
 [ 3  6  0]
 [ 3  6  1]
 [ 3  6  2]
 [ 3  8  0]
 [ 3  8  1]
 [ 3  8  2]
 [ 3 10  0]
 [ 3 10  1]
 [ 3 10  2]
 [ 4  0  0]
 [ 4  0  1]
 [ 4  0  2]
 [ 4  3  0]
 [ 4  3  1]
 [ 4  3  2]
 [ 4  4  0]
 [ 4  4  1]
 [ 4  4  2]
 [ 4  6  0]
 [ 4  6  1]
 [ 4  6  2]
 [ 4  8  0]
 [ 4  8  1]
 [ 4  8  2]
 [ 4 10  0]
 [ 4 10  1]
 [ 4